# Env definition file for creating environment via conda

name: cmatools-tests-env
channels:
 - conda-forge
dependencies:
 - python=3.9
 - iris>=3.0
 - black
 - nccmp
 - coverage
 - pytest
 - pytest-cov
 - sphinx
 - sphinx_rtd_theme
 - sphinx-argparse
 - sphinx-gallery
 - pip

 - pip:
   - sphinxcontrib-mermaid