# #################################################################################################################
# GitHub workflow action file
# Runs the end to end tests against the installed system on the runner
# #################################################################################################################

# Name for workflow (also displayed on the associated badges)
name: end-to-end-tests

# on: controls when the action will run. Triggers the workflow on push or pull request events
# Limits run only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Set environment variables so this workflow action is easy to re-use in other repos
env:
  REPO_NAME: cmatools
  CONDA_ENV: cmatools-tests-env # Name is set in the $ENV_FILE
  ENV_FILE: environment_tests.yml
  PACKAGE: cmatools # Name of package directory within repo

jobs:
  run-tests:
    timeout-minutes: 5 # Limit total time use of the workflow action, in case of problems
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # checkout code to the runner workspace root
    - name: Install dependencies
      run: |
        conda update conda
        conda env create -f $ENV_FILE
    - name: conda check
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        which python
        python --version
        conda info --envs
        conda info
    - name: Install pckage
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        pip install .
    - name: Run unit tests
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        cd scripts/tests
        chmod +x test-end-to-end.sh
        ./test-end-to-end.sh