# #################################################################################################################
# GitHub workflow action file
# Runs the unit tests against the installed system on the runner
# #################################################################################################################


# Name for workflow (also displayed on the associated badges)
name: unit-tests

# on: controls when the action will run. Triggers the workflow on push or pull request events
# Limits run only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Set environment variables so this workflow action is easy to re-use in other repos
env:
  REPO_NAME: cmatools
  CONDA_ENV: cmatools-tests-env # Name is set in the $ENV_FILE
  ENV_FILE: environment_tests.yml

jobs:
  run-tests:
    timeout-minutes: 10 # Limit total time use of the workflow action, in case of problems
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # checkout code to the runner workspace root
    - name: Install dependencies
      run: |
        conda update conda
        conda env create -f $ENV_FILE
    - name: conda check
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        which python
        python --version
        conda info --envs
        conda info
    - name: Install cmatools
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        pip install .
    - name: Run unit tests
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        cd scripts/tests
        chmod +x test-unit.sh
        ./test-unit.sh
    - name: Test with coverage
      # Re-run the tests and report test coverage
      # Does not fail with error code if any tests fail, output is for info only
      # The separate step is also needed to ensure the job fails if there are failing tests
      # This enables the code coverage stats to be visible via the actions workflow page on GitHub
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate $CONDA_ENV
        cd scripts/tests
        chmod +x coverage-unit.sh
        ./coverage-unit.sh
        #echo "$PWD"
        #cd $GITHUB_WORKSPACE
        #cd $GITHUB_WORKSPACE
        #echo "$PWD"
        #pytest --cov-report term-missing:skip-covered --trace --cov=$GITHUB_WORKSPACE/cmatools $GITHUB_WORKSPACE/tests/unit
        #below call works locally via script
        #pytest --cov-report term-missing:skip-covered --cov="${CODE_DIR}"/cmatools "${TESTS_DIR}"/unit
      env:
        REMOTE_TESTS: True